version: '3'
services:
  eve-equinox-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
